// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Talapker.Infrastructure.Data;

#nullable disable

namespace Talapker.Infrastructure.Migrations
{
    [DbContext(typeof(TalapkerDbContext))]
    partial class TalapkerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EducationGroupUntPair", b =>
                {
                    b.Property<Guid>("EducationGroupsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UntSubjectsPairsId")
                        .HasColumnType("uuid");

                    b.HasKey("EducationGroupsId", "UntSubjectsPairsId");

                    b.HasIndex("UntSubjectsPairsId");

                    b.ToTable("EducationGroupUntPair");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator().HasValue("IdentityRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("text");

                    b.Property<string>("ClientType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConsentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text");

                    b.Property<string>("JsonWebKeySet")
                        .HasColumnType("text");

                    b.Property<string>("Permissions")
                        .HasColumnType("text");

                    b.Property<string>("PostLogoutRedirectUris")
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("RedirectUris")
                        .HasColumnType("text");

                    b.Property<string>("Requirements")
                        .HasColumnType("text");

                    b.Property<string>("Settings")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("OpenIddictApplications", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("Scopes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictAuthorizations", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreScope", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Descriptions")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("Resources")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("OpenIddictScopes", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<string>("AuthorizationId")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId");

                    b.HasIndex("ReferenceId")
                        .IsUnique();

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictTokens", (string)null);
                });

            modelBuilder.Entity("Talapker.Infrastructure.Data.Institution.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LogoKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("Talapker.Infrastructure.Data.Institution.EducationDirection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Degree")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("EducationDirections");
                });

            modelBuilder.Entity("Talapker.Infrastructure.Data.Institution.GrantCompetitionStatistic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CompetitionType")
                        .HasColumnType("integer");

                    b.Property<Guid>("EducationGroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("MinScore")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EducationGroupId");

                    b.HasIndex("Year", "EducationGroupId", "CompetitionType")
                        .IsUnique();

                    b.ToTable("GrantCompetitionStatistics");
                });

            modelBuilder.Entity("Talapker.Infrastructure.Data.Institution.InstitutionEntity.EducationField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EducationDirectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EducationDirectionId");

                    b.HasIndex("NationalCode")
                        .IsUnique();

                    b.ToTable("EducationFields");
                });

            modelBuilder.Entity("Talapker.Infrastructure.Data.Institution.InstitutionEntity.EducationGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EducationFieldId")
                        .HasColumnType("uuid");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EducationFieldId");

                    b.HasIndex("NationalCode")
                        .IsUnique();

                    b.ToTable("EducationGroups");
                });

            modelBuilder.Entity("Talapker.Infrastructure.Data.Institution.InstitutionEntity.EducationProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EducationGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EducationGroupId");

                    b.HasIndex("FacultyId");

                    b.ToTable("EducationPrograms");
                });

            modelBuilder.Entity("Talapker.Infrastructure.Data.Institution.InstitutionEntity.Faculty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.ToTable("faculties", (string)null);
                });

            modelBuilder.Entity("Talapker.Infrastructure.Data.Institution.InstitutionEntity.Institution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Coordinates")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("HasHousing")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasMilitaryDepartment")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("MinCostPerYear")
                        .HasColumnType("bigint");

                    b.Property<int>("NationalCode")
                        .HasColumnType("integer");

                    b.Property<int>("StudentsCount")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("WebSiteUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("NationalCode")
                        .IsUnique();

                    b.ToTable("Institutions", (string)null);
                });

            modelBuilder.Entity("Talapker.Infrastructure.Data.Institution.InstitutionEntity.UntPair", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FirstSubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SecondSubjectId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SeedId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FirstSubjectId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("SecondSubjectId");

                    b.ToTable("UntPairs", (string)null);
                });

            modelBuilder.Entity("Talapker.Infrastructure.Data.Institution.InstitutionEntity.UntSubject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("description");

                    b.Property<int?>("SeedId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("UntSubjects", (string)null);
                });

            modelBuilder.Entity("Talapker.Infrastructure.Data.UserAccess.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarKey")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Talapker.Infrastructure.Data.UserAccess.ApplicationRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.HasDiscriminator().HasValue("ApplicationRole");
                });

            modelBuilder.Entity("EducationGroupUntPair", b =>
                {
                    b.HasOne("Talapker.Infrastructure.Data.Institution.InstitutionEntity.EducationGroup", null)
                        .WithMany()
                        .HasForeignKey("EducationGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Talapker.Infrastructure.Data.Institution.InstitutionEntity.UntPair", null)
                        .WithMany()
                        .HasForeignKey("UntSubjectsPairsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Talapker.Infrastructure.Data.UserAccess.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Talapker.Infrastructure.Data.UserAccess.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Talapker.Infrastructure.Data.UserAccess.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Talapker.Infrastructure.Data.UserAccess.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Authorizations")
                        .HasForeignKey("ApplicationId");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationId");

                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", "Authorization")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationId");

                    b.Navigation("Application");

                    b.Navigation("Authorization");
                });

            modelBuilder.Entity("Talapker.Infrastructure.Data.Institution.City", b =>
                {
                    b.OwnsOne("Talapker.Infrastructure.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<Guid>("CityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Kk")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CityId");

                            b1.ToTable("Cities");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("CityId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Talapker.Infrastructure.Data.Institution.EducationDirection", b =>
                {
                    b.OwnsOne("Talapker.Infrastructure.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<Guid>("EducationDirectionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Kk")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("EducationDirectionId");

                            b1.ToTable("EducationDirections");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("EducationDirectionId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Talapker.Infrastructure.Data.Institution.GrantCompetitionStatistic", b =>
                {
                    b.HasOne("Talapker.Infrastructure.Data.Institution.InstitutionEntity.EducationGroup", "EducationGroup")
                        .WithMany("GrantCompetitionStatistics")
                        .HasForeignKey("EducationGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Talapker.Infrastructure.Data.Institution.GrantCompetitionRecord", "Records", b1 =>
                        {
                            b1.Property<Guid>("GrantCompetitionStatisticId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("Score")
                                .HasColumnType("integer");

                            b1.Property<int>("UniversityCode")
                                .HasColumnType("integer");

                            b1.HasKey("GrantCompetitionStatisticId", "__synthesizedOrdinal");

                            b1.ToTable("GrantCompetitionStatistics");

                            b1.ToJson("Records");

                            b1.WithOwner()
                                .HasForeignKey("GrantCompetitionStatisticId");
                        });

                    b.Navigation("EducationGroup");

                    b.Navigation("Records");
                });

            modelBuilder.Entity("Talapker.Infrastructure.Data.Institution.InstitutionEntity.EducationField", b =>
                {
                    b.HasOne("Talapker.Infrastructure.Data.Institution.EducationDirection", "EducationDirection")
                        .WithMany("EducationFields")
                        .HasForeignKey("EducationDirectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Talapker.Infrastructure.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<Guid>("EducationFieldId")
                                .HasColumnType("uuid");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Kk")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("EducationFieldId");

                            b1.ToTable("EducationFields");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("EducationFieldId");
                        });

                    b.Navigation("EducationDirection");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Talapker.Infrastructure.Data.Institution.InstitutionEntity.EducationGroup", b =>
                {
                    b.HasOne("Talapker.Infrastructure.Data.Institution.InstitutionEntity.EducationField", "EducationField")
                        .WithMany("EducationGroups")
                        .HasForeignKey("EducationFieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Talapker.Infrastructure.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<Guid>("EducationGroupId")
                                .HasColumnType("uuid");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Kk")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("EducationGroupId");

                            b1.ToTable("EducationGroups");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("EducationGroupId");
                        });

                    b.Navigation("EducationField");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Talapker.Infrastructure.Data.Institution.InstitutionEntity.EducationProgram", b =>
                {
                    b.HasOne("Talapker.Infrastructure.Data.Institution.InstitutionEntity.EducationGroup", "EducationGroup")
                        .WithMany("EducationPrograms")
                        .HasForeignKey("EducationGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Talapker.Infrastructure.Data.Institution.InstitutionEntity.Faculty", "Faculty")
                        .WithMany("EducationPrograms")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Talapker.Infrastructure.LocalizedText", "Description", b1 =>
                        {
                            b1.Property<Guid>("EducationProgramId")
                                .HasColumnType("uuid");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Kk")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("EducationProgramId");

                            b1.ToTable("EducationPrograms");

                            b1.ToJson("Description");

                            b1.WithOwner()
                                .HasForeignKey("EducationProgramId");
                        });

                    b.OwnsOne("Talapker.Infrastructure.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<Guid>("EducationProgramId")
                                .HasColumnType("uuid");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Kk")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("EducationProgramId");

                            b1.ToTable("EducationPrograms");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("EducationProgramId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("EducationGroup");

                    b.Navigation("Faculty");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Talapker.Infrastructure.Data.Institution.InstitutionEntity.Faculty", b =>
                {
                    b.HasOne("Talapker.Infrastructure.Data.Institution.InstitutionEntity.Institution", "Institution")
                        .WithMany("Faculties")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("Talapker.Infrastructure.Data.Institution.InstitutionEntity.Institution", b =>
                {
                    b.HasOne("Talapker.Infrastructure.Data.Institution.City", "City")
                        .WithMany("Institutions")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Talapker.Infrastructure.LocalizedText", "Description", b1 =>
                        {
                            b1.Property<Guid>("InstitutionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Kk")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("InstitutionId");

                            b1.ToTable("Institutions");

                            b1.ToJson("Description");

                            b1.WithOwner()
                                .HasForeignKey("InstitutionId");
                        });

                    b.OwnsOne("Talapker.Infrastructure.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<Guid>("InstitutionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Kk")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("InstitutionId");

                            b1.ToTable("Institutions");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("InstitutionId");
                        });

                    b.OwnsMany("Talapker.Infrastructure.Data.Institution.InstitutionEntity.InstitutionAdvantage", "Advantages", b1 =>
                        {
                            b1.Property<Guid>("InstitutionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.HasKey("InstitutionId", "__synthesizedOrdinal");

                            b1.ToTable("Institutions");

                            b1.ToJson("Advantages");

                            b1.WithOwner()
                                .HasForeignKey("InstitutionId");

                            b1.OwnsOne("Talapker.Infrastructure.LocalizedText", "Description", b2 =>
                                {
                                    b2.Property<Guid>("InstitutionAdvantageInstitutionId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("InstitutionAdvantage__synthesizedOrdinal")
                                        .HasColumnType("integer");

                                    b2.Property<string>("En")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Kk")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Ru")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("InstitutionAdvantageInstitutionId", "InstitutionAdvantage__synthesizedOrdinal");

                                    b2.ToTable("Institutions");

                                    b2.ToJson("Description");

                                    b2.WithOwner()
                                        .HasForeignKey("InstitutionAdvantageInstitutionId", "InstitutionAdvantage__synthesizedOrdinal");
                                });

                            b1.OwnsOne("Talapker.Infrastructure.LocalizedText", "Title", b2 =>
                                {
                                    b2.Property<Guid>("InstitutionAdvantageInstitutionId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("InstitutionAdvantage__synthesizedOrdinal")
                                        .HasColumnType("integer");

                                    b2.Property<string>("En")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Kk")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Ru")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("InstitutionAdvantageInstitutionId", "InstitutionAdvantage__synthesizedOrdinal");

                                    b2.ToTable("Institutions");

                                    b2.ToJson("Title");

                                    b2.WithOwner()
                                        .HasForeignKey("InstitutionAdvantageInstitutionId", "InstitutionAdvantage__synthesizedOrdinal");
                                });

                            b1.Navigation("Description")
                                .IsRequired();

                            b1.Navigation("Title")
                                .IsRequired();
                        });

                    b.Navigation("Advantages");

                    b.Navigation("City");

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Talapker.Infrastructure.Data.Institution.InstitutionEntity.UntPair", b =>
                {
                    b.HasOne("Talapker.Infrastructure.Data.Institution.InstitutionEntity.UntSubject", "FirstSubject")
                        .WithMany()
                        .HasForeignKey("FirstSubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Talapker.Infrastructure.Data.Institution.InstitutionEntity.UntSubject", "SecondSubject")
                        .WithMany()
                        .HasForeignKey("SecondSubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FirstSubject");

                    b.Navigation("SecondSubject");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("Talapker.Infrastructure.Data.Institution.City", b =>
                {
                    b.Navigation("Institutions");
                });

            modelBuilder.Entity("Talapker.Infrastructure.Data.Institution.EducationDirection", b =>
                {
                    b.Navigation("EducationFields");
                });

            modelBuilder.Entity("Talapker.Infrastructure.Data.Institution.InstitutionEntity.EducationField", b =>
                {
                    b.Navigation("EducationGroups");
                });

            modelBuilder.Entity("Talapker.Infrastructure.Data.Institution.InstitutionEntity.EducationGroup", b =>
                {
                    b.Navigation("EducationPrograms");

                    b.Navigation("GrantCompetitionStatistics");
                });

            modelBuilder.Entity("Talapker.Infrastructure.Data.Institution.InstitutionEntity.Faculty", b =>
                {
                    b.Navigation("EducationPrograms");
                });

            modelBuilder.Entity("Talapker.Infrastructure.Data.Institution.InstitutionEntity.Institution", b =>
                {
                    b.Navigation("Faculties");
                });
#pragma warning restore 612, 618
        }
    }
}
