<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Talapker.Infrastructure\Talapker.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Talapker.Notifications.Contracts\Talapker.Notifications.Contracts.csproj" />
  </ItemGroup>

</Project>
